.class public abstract Lcom/lody/virtual/client/stub/ShadowActivityPIP;
.super Lcom/lody/virtual/client/stub/ShadowActivity;
.source "ShadowActivityPIP.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P99;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P98;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P97;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P96;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P95;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P94;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P93;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P92;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P91;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P90;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P89;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P88;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P87;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P86;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P85;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P84;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P83;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P82;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P81;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P80;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P79;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P78;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P77;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P76;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P75;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P74;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P73;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P72;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P71;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P70;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P69;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P68;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P67;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P66;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P65;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P64;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P63;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P62;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P61;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P60;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P59;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P58;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P57;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P56;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P55;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P54;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P53;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P52;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P51;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P50;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P49;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P48;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P47;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P46;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P45;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P44;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P43;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P42;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P41;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P40;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P39;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P38;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P37;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P36;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P35;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P34;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P33;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P32;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P31;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P30;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P29;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P28;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P27;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P26;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P25;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P24;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P23;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P22;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P21;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P20;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P19;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P18;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P17;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P16;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P15;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P14;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P13;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P12;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P11;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P10;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P9;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P8;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P7;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P6;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P5;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P4;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P3;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P2;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P1;,
        Lcom/lody/virtual/client/stub/ShadowActivityPIP$P0;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 1
    invoke-direct {p0}, Lcom/lody/virtual/client/stub/ShadowActivity;-><init>()V

    return-void
.end method
