.class public abstract Lcom/lody/virtual/client/stub/ShadowDialogActivity;
.super Lcom/lody/virtual/client/stub/ShadowActivity;
.source "ShadowDialogActivity.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P99;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P98;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P97;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P96;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P95;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P94;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P93;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P92;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P91;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P90;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P89;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P88;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P87;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P86;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P85;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P84;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P83;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P82;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P81;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P80;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P79;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P78;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P77;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P76;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P75;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P74;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P73;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P72;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P71;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P70;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P69;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P68;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P67;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P66;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P65;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P64;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P63;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P62;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P61;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P60;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P59;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P58;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P57;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P56;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P55;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P54;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P53;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P52;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P51;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P50;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P49;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P48;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P47;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P46;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P45;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P44;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P43;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P42;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P41;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P40;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P39;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P38;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P37;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P36;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P35;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P34;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P33;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P32;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P31;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P30;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P29;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P28;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P27;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P26;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P25;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P24;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P23;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P22;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P21;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P20;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P19;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P18;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P17;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P16;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P15;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P14;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P13;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P12;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P11;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P10;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P9;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P8;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P7;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P6;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P5;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P4;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P3;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P2;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P1;,
        Lcom/lody/virtual/client/stub/ShadowDialogActivity$P0;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 1
    invoke-direct {p0}, Lcom/lody/virtual/client/stub/ShadowActivity;-><init>()V

    return-void
.end method
